on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
          python3 cmake unzip ninja-build curl xz-utils
        
      - name: Install emscripten
        run: |
          pwd
          curl -L -o emsdk.zip https://github.com/emscripten-core/emsdk/archive/refs/tags/4.0.21.zip
          unzip emsdk.zip
          cd emsdk-4.0.21
          ./emsdk install latest
          ./emsdk activate latest

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build project
        shell: bash
        run: |
          set -e
          pwd
          cd ${{ github.workspace }}
          source ./emsdk-4.0.21/emsdk_env.sh
          emcmake cmake -S . -B out/build/web -G Ninja -DPLATFORM=Web
          cmake --build out/build/web
          mkdir -p ./dist
          mv out/build/web/Tetris.* ./dist
          mv /app/dist/Tetris.html ./dist/index.html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: /app/dist

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4